/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u32)]
pub enum AfXdpMode {
	 AF_XDP_API_MODE_AUTO=0,
	 AF_XDP_API_MODE_COPY=1,
	 AF_XDP_API_MODE_ZERO_COPY=2,
}
impl Default for AfXdpMode {
	fn default() -> Self { AfXdpMode::AF_XDP_API_MODE_AUTO }
}
#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq)]
pub enum AfXdpFlag {
	 AF_XDP_API_FLAGS_NO_SYSCALL_LOCK=1,
}
impl Default for AfXdpFlag {
	fn default() -> Self { AfXdpFlag::AF_XDP_API_FLAGS_NO_SYSCALL_LOCK }
}
impl AsEnumFlag for AfXdpFlag {
	 fn as_u32(data: &Self) -> u32{
		 *data as u32
	 }
	 fn from_u32(data: u32) -> Self{
		 match data{
			 1 => AfXdpFlag::AF_XDP_API_FLAGS_NO_SYSCALL_LOCK,
			_ => panic!("Invalid Enum Descriminant")
		 }
	 }
	 fn size_of_enum_flag() -> u32{
		 8 as u32
	}
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(af_xdp_create_v3_cf4b1827)]
pub struct AfXdpCreateV3 {
	pub client_index: u32,
	pub context: u32,
	pub host_if: FixedSizeString<typenum::U64>,
	pub name: FixedSizeString<typenum::U64>,
	pub rxq_num: u16,
	pub rxq_size: u16,
	pub txq_size: u16,
	pub mode: AfXdpMode,
	 pub flags: EnumFlag<AfXdpFlag>,
	pub prog: FixedSizeString<typenum::U256>,
	pub netns: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(af_xdp_create_v3_reply_5383d31f)]
pub struct AfXdpCreateV3Reply {
	pub context: u32,
	pub retval: i32,
	pub sw_if_index: InterfaceIndex,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(af_xdp_delete_f9e6675e)]
pub struct AfXdpDelete {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_index: InterfaceIndex,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(af_xdp_delete_reply_e8d4e804)]
pub struct AfXdpDeleteReply {
	pub context: u32,
	pub retval: i32,
}
