/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
use crate::ethernet_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(arping_48817482)]
pub struct Arping {
	pub client_index: u32,
	pub context: u32,
	pub address: Address,
	pub sw_if_index: InterfaceIndex,
	pub is_garp: bool,
	pub repeat: u32,
	pub interval: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(arping_reply_bb9d1cbd)]
pub struct ArpingReply {
	pub context: u32,
	pub retval: i32,
	pub reply_count: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(arping_acd_48817482)]
pub struct ArpingAcd {
	pub client_index: u32,
	pub context: u32,
	pub address: Address,
	pub sw_if_index: InterfaceIndex,
	pub is_garp: bool,
	pub repeat: u32,
	pub interval: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(arping_acd_reply_e08c3b05)]
pub struct ArpingAcdReply {
	pub context: u32,
	pub retval: i32,
	pub reply_count: u32,
	pub mac_address: MacAddress,
}
