/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::fib_types::*;
// Implementation for bier_table_id
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct BierTableId {
	pub bt_set: u8,
	pub bt_sub_domain: u8,
	pub bt_hdr_len_id: u8,
}
// Implementation for bier_route
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct BierRoute {
	pub br_bp: u32,
	pub br_tbl_id: BierTableId,
	pub br_n_paths: u8,
	pub br_paths: VariableSizeArray<FibPath>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_table_add_del_35e59209)]
pub struct BierTableAddDel {
	pub client_index: u32,
	pub context: u32,
	pub bt_tbl_id: BierTableId,
	pub bt_label: u32,
	pub bt_is_add: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_table_add_del_reply_e8d4e804)]
pub struct BierTableAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_table_dump_51077d14)]
pub struct BierTableDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_table_details_fc44a9dd)]
pub struct BierTableDetails {
	pub context: u32,
	pub bt_label: u32,
	pub bt_tbl_id: BierTableId,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_route_add_del_fd02f3ea)]
pub struct BierRouteAddDel {
	pub client_index: u32,
	pub context: u32,
	pub br_is_add: bool,
	pub br_is_replace: bool,
	pub br_route: BierRoute,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_route_add_del_reply_e8d4e804)]
pub struct BierRouteAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_route_dump_38339846)]
pub struct BierRouteDump {
	pub client_index: u32,
	pub context: u32,
	pub br_tbl_id: BierTableId,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_route_details_4008caee)]
pub struct BierRouteDetails {
	pub context: u32,
	pub br_route: BierRoute,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_imp_add_3856dc3d)]
pub struct BierImpAdd {
	pub client_index: u32,
	pub context: u32,
	pub bi_tbl_id: BierTableId,
	pub bi_src: u16,
	pub bi_n_bytes: u8,
	pub bi_bytes: VariableSizeArray<u8>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_imp_add_reply_d49c5793)]
pub struct BierImpAddReply {
	pub context: u32,
	pub retval: i32,
	pub bi_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_imp_del_7d45edf6)]
pub struct BierImpDel {
	pub client_index: u32,
	pub context: u32,
	pub bi_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_imp_del_reply_e8d4e804)]
pub struct BierImpDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_imp_dump_51077d14)]
pub struct BierImpDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_imp_details_b76192df)]
pub struct BierImpDetails {
	pub context: u32,
	pub bi_tbl_id: BierTableId,
	pub bi_src: u16,
	pub bi_n_bytes: u8,
	pub bi_bytes: VariableSizeArray<u8>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_table_add_del_889657ac)]
pub struct BierDispTableAddDel {
	pub client_index: u32,
	pub context: u32,
	pub bdt_tbl_id: u32,
	pub bdt_is_add: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_table_add_del_reply_e8d4e804)]
pub struct BierDispTableAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_table_dump_51077d14)]
pub struct BierDispTableDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_table_details_d27942c0)]
pub struct BierDispTableDetails {
	pub context: u32,
	pub bdt_tbl_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_entry_add_del_9eb80cb4)]
pub struct BierDispEntryAddDel {
	pub client_index: u32,
	pub context: u32,
	pub bde_bp: u16,
	pub bde_tbl_id: u32,
	pub bde_is_add: bool,
	pub bde_payload_proto: u8,
	pub bde_n_paths: u8,
	pub bde_paths: VariableSizeArray<FibPath>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_entry_add_del_reply_e8d4e804)]
pub struct BierDispEntryAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_entry_dump_b5fa54ad)]
pub struct BierDispEntryDump {
	pub client_index: u32,
	pub context: u32,
	pub bde_tbl_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(bier_disp_entry_details_84c218f1)]
pub struct BierDispEntryDetails {
	pub context: u32,
	pub bde_bp: u16,
	pub bde_tbl_id: u32,
	pub bde_is_add: bool,
	pub bde_payload_proto: u8,
	pub bde_n_paths: u8,
	pub bde_paths: VariableSizeArray<FibPath>,
}
