/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
// Implementation for ikev2_id
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Id {
	pub typ: u8,
	pub data_len: u8,
	pub data: FixedSizeString<typenum::U64>,
}
// Implementation for ikev2_ts
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Ts {
	pub sa_index: u32,
	pub child_sa_index: u32,
	pub is_local: bool,
	pub protocol_id: u8,
	pub start_port: u16,
	pub end_port: u16,
	pub start_addr: Address,
	pub end_addr: Address,
}
// Implementation for ikev2_auth
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Auth {
	pub method: u8,
	pub hex: u8,
	pub data_len: u32,
	pub data: VariableSizeArray<u8>,
}
// Implementation for ikev2_responder
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Responder {
	pub sw_if_index: InterfaceIndex,
	pub addr: Address,
}
// Implementation for ikev2_ike_transforms
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2IkeTransforms {
	pub crypto_alg: u8,
	pub crypto_key_size: u32,
	pub integ_alg: u8,
	pub dh_group: u8,
}
// Implementation for ikev2_esp_transforms
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2EspTransforms {
	pub crypto_alg: u8,
	pub crypto_key_size: u32,
	pub integ_alg: u8,
}
// Implementation for ikev2_profile
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Profile {
	pub name: FixedSizeString<typenum::U64>,
	pub loc_id: Ikev2Id,
	pub rem_id: Ikev2Id,
	pub loc_ts: Ikev2Ts,
	pub rem_ts: Ikev2Ts,
	pub responder: Ikev2Responder,
	pub ike_ts: Ikev2IkeTransforms,
	pub esp_ts: Ikev2EspTransforms,
	pub lifetime: u64,
	pub lifetime_maxdata: u64,
	pub lifetime_jitter: u32,
	pub handover: u32,
	pub ipsec_over_udp_port: u16,
	pub tun_itf: u32,
	pub udp_encap: bool,
	pub natt_disabled: bool,
	pub auth: Ikev2Auth,
}
// Implementation for ikev2_sa_transform
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2SaTransform {
	pub transform_type: u8,
	pub transform_id: u16,
	pub key_len: u16,
	pub key_trunc: u16,
	pub block_size: u16,
	pub dh_group: u8,
}
// Implementation for ikev2_keys
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Keys {
	pub sk_d: FixedSizeArray<u8, typenum::U64>,
	pub sk_d_len: u8,
	pub sk_ai: FixedSizeArray<u8, typenum::U64>,
	pub sk_ai_len: u8,
	pub sk_ar: FixedSizeArray<u8, typenum::U64>,
	pub sk_ar_len: u8,
	pub sk_ei: FixedSizeArray<u8, typenum::U64>,
	pub sk_ei_len: u8,
	pub sk_er: FixedSizeArray<u8, typenum::U64>,
	pub sk_er_len: u8,
	pub sk_pi: FixedSizeArray<u8, typenum::U64>,
	pub sk_pi_len: u8,
	pub sk_pr: FixedSizeArray<u8, typenum::U64>,
	pub sk_pr_len: u8,
}
// Implementation for ikev2_child_sa
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2ChildSa {
	pub sa_index: u32,
	pub child_sa_index: u32,
	pub i_spi: u32,
	pub r_spi: u32,
	pub keys: Ikev2Keys,
	pub encryption: Ikev2SaTransform,
	pub integrity: Ikev2SaTransform,
	pub esn: Ikev2SaTransform,
}
// Implementation for ikev2_child_sa_v2
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2ChildSaV2 {
	pub sa_index: u32,
	pub child_sa_index: u32,
	pub i_spi: u32,
	pub r_spi: u32,
	pub keys: Ikev2Keys,
	pub encryption: Ikev2SaTransform,
	pub integrity: Ikev2SaTransform,
	pub esn: Ikev2SaTransform,
	pub uptime: f64,
}
// Implementation for ikev2_sa_stats
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2SaStats {
	pub n_keepalives: u16,
	pub n_rekey_req: u16,
	pub n_sa_init_req: u16,
	pub n_sa_auth_req: u16,
	pub n_retransmit: u16,
	pub n_init_sa_retransmit: u16,
}
// Implementation for ikev2_sa
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2Sa {
	pub sa_index: u32,
	pub profile_index: u32,
	pub ispi: u64,
	pub rspi: u64,
	pub iaddr: Address,
	pub raddr: Address,
	pub keys: Ikev2Keys,
	pub i_id: Ikev2Id,
	pub r_id: Ikev2Id,
	pub encryption: Ikev2SaTransform,
	pub integrity: Ikev2SaTransform,
	pub prf: Ikev2SaTransform,
	pub dh: Ikev2SaTransform,
	pub stats: Ikev2SaStats,
}
// Implementation for ikev2_sa_v2
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2SaV2 {
	pub sa_index: u32,
	pub profile_name: FixedSizeString<typenum::U64>,
	pub state: Ikev2State,
	pub ispi: u64,
	pub rspi: u64,
	pub iaddr: Address,
	pub raddr: Address,
	pub keys: Ikev2Keys,
	pub i_id: Ikev2Id,
	pub r_id: Ikev2Id,
	pub encryption: Ikev2SaTransform,
	pub integrity: Ikev2SaTransform,
	pub prf: Ikev2SaTransform,
	pub dh: Ikev2SaTransform,
	pub stats: Ikev2SaStats,
}
// Implementation for ikev2_sa_v3
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Ikev2SaV3 {
	pub sa_index: u32,
	pub profile_name: FixedSizeString<typenum::U64>,
	pub state: Ikev2State,
	pub ispi: u64,
	pub rspi: u64,
	pub iaddr: Address,
	pub raddr: Address,
	pub keys: Ikev2Keys,
	pub i_id: Ikev2Id,
	pub r_id: Ikev2Id,
	pub encryption: Ikev2SaTransform,
	pub integrity: Ikev2SaTransform,
	pub prf: Ikev2SaTransform,
	pub dh: Ikev2SaTransform,
	pub stats: Ikev2SaStats,
	pub uptime: f64,
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u32)]
pub enum Ikev2State {
	 UNKNOWN=0,
	 SA_INIT=1,
	 DELETED=2,
	 AUTH_FAILED=3,
	 AUTHENTICATED=4,
	 NOTIFY_AND_DELETE=5,
	 TS_UNACCEPTABLE=6,
	 NO_PROPOSAL_CHOSEN=7,
}
impl Default for Ikev2State {
	fn default() -> Self { Ikev2State::UNKNOWN }
}
