/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum Ip6DadState {
	 IP6_DAD_STATE_IDLE=0,
	 IP6_DAD_STATE_TENTATIVE=1,
	 IP6_DAD_STATE_PREFERRED=2,
	 IP6_DAD_STATE_DUPLICATE=3,
}
impl Default for Ip6DadState {
	fn default() -> Self { Ip6DadState::IP6_DAD_STATE_IDLE }
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip6_dad_enable_disable_557ed29b)]
pub struct Ip6DadEnableDisable {
	pub client_index: u32,
	pub context: u32,
	pub enable: bool,
	pub dad_transmits: u8,
	pub dad_retransmit_delay: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip6_dad_enable_disable_reply_e8d4e804)]
pub struct Ip6DadEnableDisableReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip6_dad_dump_51077d14)]
pub struct Ip6DadDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip6_dad_details_f6971ec4)]
pub struct Ip6DadDetails {
	pub context: u32,
	pub enabled: bool,
	pub dad_transmits: u8,
	pub dad_retransmit_delay: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(want_ip6_dad_events_c5e2af94)]
pub struct WantIp6DadEvents {
	pub client_index: u32,
	pub context: u32,
	pub enable_disable: bool,
	pub pid: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(want_ip6_dad_events_reply_e8d4e804)]
pub struct WantIp6DadEventsReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip6_dad_event_d6037980)]
pub struct Ip6DadEvent {
	pub client_index: u32,
	pub pid: u32,
	pub state: Ip6DadState,
	pub sw_if_index: InterfaceIndex,
	pub address: Ip6Address,
	pub dad_count: u8,
	pub dad_transmits: u8,
}
