/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::fib_types::*;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_add_2f78ffda)]
pub struct IpSessionRedirectAdd {
	pub client_index: u32,
	pub context: u32,
	pub table_index: u32,
	pub match_len: u8,
	pub mach: FixedSizeArray<u8, typenum::U80>,
	pub opaque_index: u32,
	pub is_punt: bool,
	pub n_paths: u8,
	pub paths: VariableSizeArray<FibPath>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_add_reply_e8d4e804)]
pub struct IpSessionRedirectAddReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_add_v2_0765f51f)]
pub struct IpSessionRedirectAddV2 {
	pub client_index: u32,
	pub context: u32,
	pub table_index: u32,
	pub opaque_index: u32,
	pub proto: FibPathNhProto,
	pub is_punt: bool,
	pub match_len: u8,
	pub mach: FixedSizeArray<u8, typenum::U80>,
	pub n_paths: u8,
	pub paths: VariableSizeArray<FibPath>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_add_v2_reply_e8d4e804)]
pub struct IpSessionRedirectAddV2Reply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_del_fb643388)]
pub struct IpSessionRedirectDel {
	pub client_index: u32,
	pub context: u32,
	pub table_index: u32,
	pub match_len: u8,
	pub mach: VariableSizeArray<u8>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_del_reply_e8d4e804)]
pub struct IpSessionRedirectDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_dump_33554253)]
pub struct IpSessionRedirectDump {
	pub client_index: u32,
	pub context: u32,
	pub table_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ip_session_redirect_details_4487a233)]
pub struct IpSessionRedirectDetails {
	pub context: u32,
	pub retval: i32,
	pub table_index: u32,
	pub opaque_index: u32,
	pub is_punt: bool,
	pub is_ip6: bool,
	pub match_length: u32,
	pub mach: FixedSizeArray<u8, typenum::U80>,
	pub n_paths: u8,
	pub paths: VariableSizeArray<FibPath>,
}
