/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_nat_set_external_interface_fca1e31a)]
pub struct SfdpNatSetExternalInterface {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_index: InterfaceIndex,
	pub tenant_id: u32,
	pub is_disable: u8,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_nat_set_external_interface_reply_e8d4e804)]
pub struct SfdpNatSetExternalInterfaceReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_nat_alloc_pool_add_del_6ca85aad)]
pub struct SfdpNatAllocPoolAddDel {
	pub client_index: u32,
	pub context: u32,
	pub alloc_pool_id: u32,
	pub is_del: u8,
	pub n_addr: u32,
	pub addr: VariableSizeArray<Ip4Address>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_nat_alloc_pool_add_del_reply_e8d4e804)]
pub struct SfdpNatAllocPoolAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_nat_snat_set_unset_7f07225d)]
pub struct SfdpNatSnatSetUnset {
	pub client_index: u32,
	pub context: u32,
	pub tenant_id: u32,
	pub outside_tenant_id: u32,
	pub table_id: u32,
	pub alloc_pool_id: u32,
	pub is_disable: u8,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_nat_snat_set_unset_reply_e8d4e804)]
pub struct SfdpNatSnatSetUnsetReply {
	pub context: u32,
	pub retval: i32,
}
