/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::fib_types::*;
// Implementation for npol_three_tuple
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolThreeTuple {
	pub address: Address,
	pub l4_proto: u8,
	pub port: u16,
}
// Implementation for npol_ipset_member
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolIpsetMember {
	pub val: NpolIpsetMemberVal,
}
// Implementation for npol_port_range
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolPortRange {
	pub start: u16,
	pub end: u16,
}
// Implementation for npol_entry_set_id
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolEntrySetId {
	pub set_id: u32,
}
// Implementation for npol_rule_entry
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolRuleEntry {
	pub is_src: bool,
	pub is_not: bool,
	pub typ: NpolEntryType,
	pub data: NpolEntryData,
}
// Implementation for npol_rule_filter
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolRuleFilter {
	pub value: u32,
	pub typ: NpolRuleFilterType,
	pub should_match: u8,
}
// Implementation for npol_rule
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolRule {
	pub action: NpolRuleAction,
	pub filters: FixedSizeArray<NpolRuleFilter, typenum::U3>,
	pub num_entries: u32,
	pub matches: VariableSizeArray<NpolRuleEntry>,
}
// Implementation for npol_policy_item
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NpolPolicyItem {
	pub is_inbound: bool,
	pub rule_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, Default, VppUnionIdent)]
#[types(Address:17)]
#[types(Prefix:18)]
#[types(NpolThreeTuple:20)]
pub struct NpolIpsetMemberVal(FixedSizeArray<u8, typenum::U20>);
#[derive(Debug, Clone, Serialize, Deserialize, Default, VppUnionIdent)]
#[types(Prefix:18)]
#[types(NpolPortRange:4)]
#[types(NpolEntrySetId:4)]
pub struct NpolEntryData(FixedSizeArray<u8, typenum::U18>);
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum NpolIpsetType {
	 NPOL_IP=0,
	 NPOL_IP_AND_PORT=1,
	 NPOL_NET=2,
}
impl Default for NpolIpsetType {
	fn default() -> Self { NpolIpsetType::NPOL_IP }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum NpolRuleAction {
	 NPOL_ALLOW=0,
	 NPOL_DENY=1,
	 NPOL_LOG=2,
	 NPOL_PASS=3,
}
impl Default for NpolRuleAction {
	fn default() -> Self { NpolRuleAction::NPOL_ALLOW }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum NpolEntryType {
	 NPOL_CIDR=0,
	 NPOL_PORT_RANGE=1,
	 NPOL_PORT_IP_SET=2,
	 NPOL_IP_SET=3,
}
impl Default for NpolEntryType {
	fn default() -> Self { NpolEntryType::NPOL_CIDR }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum NpolPolicyDefault {
	 NPOL_DEFAULT_ALLOW=0,
	 NPOL_DEFAULT_DENY=1,
	 NPOL_DEFAULT_PASS=2,
}
impl Default for NpolPolicyDefault {
	fn default() -> Self { NpolPolicyDefault::NPOL_DEFAULT_ALLOW }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum NpolRuleFilterType {
	 NPOL_RULE_FILTER_NONE_TYPE=0,
	 NPOL_RULE_FILTER_ICMP_TYPE=1,
	 NPOL_RULE_FILTER_ICMP_CODE=2,
	 NPOL_RULE_FILTER_L4_PROTO=3,
}
impl Default for NpolRuleFilterType {
	fn default() -> Self { NpolRuleFilterType::NPOL_RULE_FILTER_NONE_TYPE }
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_get_version_51077d14)]
pub struct NpolGetVersion {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_get_version_reply_9b32cf86)]
pub struct NpolGetVersionReply {
	pub context: u32,
	pub major: u32,
	pub minor: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_ipset_create_f948b404)]
pub struct NpolIpsetCreate {
	pub client_index: u32,
	pub context: u32,
	pub typ: NpolIpsetType,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_ipset_create_reply_6a43f193)]
pub struct NpolIpsetCreateReply {
	pub context: u32,
	pub retval: i32,
	pub set_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_ipset_add_del_members_8ad1b2ed)]
pub struct NpolIpsetAddDelMembers {
	pub client_index: u32,
	pub context: u32,
	pub set_id: u32,
	pub is_add: bool,
	pub len: u32,
	pub members: VariableSizeArray<NpolIpsetMember>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_ipset_add_del_members_reply_e8d4e804)]
pub struct NpolIpsetAddDelMembersReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_ipset_delete_ceacdbcb)]
pub struct NpolIpsetDelete {
	pub client_index: u32,
	pub context: u32,
	pub set_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_ipset_delete_reply_e8d4e804)]
pub struct NpolIpsetDeleteReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_rule_create_f113de45)]
pub struct NpolRuleCreate {
	pub client_index: u32,
	pub context: u32,
	pub rule: NpolRule,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_rule_update_e38bffe2)]
pub struct NpolRuleUpdate {
	pub client_index: u32,
	pub context: u32,
	pub rule_id: u32,
	pub rule: NpolRule,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_rule_update_reply_e8d4e804)]
pub struct NpolRuleUpdateReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_rule_create_reply_b48f8052)]
pub struct NpolRuleCreateReply {
	pub context: u32,
	pub retval: i32,
	pub rule_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_rule_delete_d19bb6be)]
pub struct NpolRuleDelete {
	pub client_index: u32,
	pub context: u32,
	pub rule_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_rule_delete_reply_e8d4e804)]
pub struct NpolRuleDeleteReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_policy_create_3441bb97)]
pub struct NpolPolicyCreate {
	pub client_index: u32,
	pub context: u32,
	pub num_items: u32,
	pub rules: VariableSizeArray<NpolPolicyItem>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_policy_create_reply_90f27405)]
pub struct NpolPolicyCreateReply {
	pub context: u32,
	pub retval: i32,
	pub policy_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_policy_update_21a5f7ef)]
pub struct NpolPolicyUpdate {
	pub client_index: u32,
	pub context: u32,
	pub policy_id: u32,
	pub num_items: u32,
	pub rules: VariableSizeArray<NpolPolicyItem>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_policy_update_reply_e8d4e804)]
pub struct NpolPolicyUpdateReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_policy_delete_ad833868)]
pub struct NpolPolicyDelete {
	pub client_index: u32,
	pub context: u32,
	pub policy_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_policy_delete_reply_e8d4e804)]
pub struct NpolPolicyDeleteReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_configure_policies_66fe1335)]
pub struct NpolConfigurePolicies {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_index: u32,
	pub num_rx_policies: u32,
	pub num_tx_policies: u32,
	pub total_ids: u32,
	pub invert_rx_tx: u8,
	pub policy_default_rx: NpolPolicyDefault,
	pub policy_default_tx: NpolPolicyDefault,
	pub profile_default_rx: NpolPolicyDefault,
	pub profile_default_tx: NpolPolicyDefault,
	pub policy_ids: VariableSizeArray<u32>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(npol_configure_policies_reply_e8d4e804)]
pub struct NpolConfigurePoliciesReply {
	pub context: u32,
	pub retval: i32,
}
