/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_add_del_entry_7dea480b)]
pub struct NshAddDelEntry {
	pub client_index: u32,
	pub context: u32,
	pub is_add: bool,
	pub nsp_nsi: u32,
	pub md_type: u8,
	pub ver_o_c: u8,
	pub ttl: u8,
	pub length: u8,
	pub next_protocol: u8,
	pub c1: u32,
	pub c2: u32,
	pub c3: u32,
	pub c4: u32,
	pub tlv_length: u8,
	pub tlv: FixedSizeArray<u8, typenum::U248>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_add_del_entry_reply_6296a9eb)]
pub struct NshAddDelEntryReply {
	pub context: u32,
	pub retval: i32,
	pub entry_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_entry_dump_cdaf8ccb)]
pub struct NshEntryDump {
	pub client_index: u32,
	pub context: u32,
	pub entry_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_entry_details_046fb556)]
pub struct NshEntryDetails {
	pub context: u32,
	pub entry_index: u32,
	pub nsp_nsi: u32,
	pub md_type: u8,
	pub ver_o_c: u8,
	pub ttl: u8,
	pub length: u8,
	pub next_protocol: u8,
	pub c1: u32,
	pub c2: u32,
	pub c3: u32,
	pub c4: u32,
	pub tlv_length: u8,
	pub tlv: FixedSizeArray<u8, typenum::U248>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_add_del_map_0a0f42b0)]
pub struct NshAddDelMap {
	pub client_index: u32,
	pub context: u32,
	pub is_add: bool,
	pub nsp_nsi: u32,
	pub mapped_nsp_nsi: u32,
	pub nsh_action: u32,
	pub sw_if_index: InterfaceIndex,
	pub rx_sw_if_index: InterfaceIndex,
	pub next_node: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_add_del_map_reply_b2b127ef)]
pub struct NshAddDelMapReply {
	pub context: u32,
	pub retval: i32,
	pub map_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_map_dump_8fc06b82)]
pub struct NshMapDump {
	pub client_index: u32,
	pub context: u32,
	pub map_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(nsh_map_details_2fefcf49)]
pub struct NshMapDetails {
	pub context: u32,
	pub map_index: u32,
	pub nsp_nsi: u32,
	pub mapped_nsp_nsi: u32,
	pub nsh_action: u32,
	pub sw_if_index: InterfaceIndex,
	pub rx_sw_if_index: InterfaceIndex,
	pub next_node: u32,
}
