/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(want_ping_finished_events_e79ee58b)]
pub struct WantPingFinishedEvents {
	pub client_index: u32,
	pub context: u32,
	pub address: Address,
	pub repeat: u32,
	pub interval: f64,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(want_ping_finished_events_reply_e8d4e804)]
pub struct WantPingFinishedEventsReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(ping_finished_event_397ccf72)]
pub struct PingFinishedEvent {
	pub client_index: u32,
	pub request_count: u32,
	pub reply_count: u32,
}
