/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
// Implementation for sse2_qos_action
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Sse2QosAction {
	pub typ: Sse2QosActionType,
	pub dscp: u8,
}
// Implementation for policer_config
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PolicerConfig {
	pub cir: u32,
	pub eir: u32,
	pub cb: u64,
	pub eb: u64,
	pub rate_type: Sse2QosRateType,
	pub round_type: Sse2QosRoundType,
	pub typ: Sse2QosPolicerType,
	pub color_aware: bool,
	pub conform_action: Sse2QosAction,
	pub exceed_action: Sse2QosAction,
	pub violate_action: Sse2QosAction,
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum Sse2QosRateType {
	 SSE2_QOS_RATE_API_KBPS=0,
	 SSE2_QOS_RATE_API_PPS=1,
	 SSE2_QOS_RATE_API_INVALID=2,
}
impl Default for Sse2QosRateType {
	fn default() -> Self { Sse2QosRateType::SSE2_QOS_RATE_API_KBPS }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum Sse2QosRoundType {
	 SSE2_QOS_ROUND_API_TO_CLOSEST=0,
	 SSE2_QOS_ROUND_API_TO_UP=1,
	 SSE2_QOS_ROUND_API_TO_DOWN=2,
	 SSE2_QOS_ROUND_API_INVALID=3,
}
impl Default for Sse2QosRoundType {
	fn default() -> Self { Sse2QosRoundType::SSE2_QOS_ROUND_API_TO_CLOSEST }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum Sse2QosPolicerType {
	 SSE2_QOS_POLICER_TYPE_API_1R2C=0,
	 SSE2_QOS_POLICER_TYPE_API_1R3C_RFC_2697=1,
	 SSE2_QOS_POLICER_TYPE_API_2R3C_RFC_2698=2,
	 SSE2_QOS_POLICER_TYPE_API_2R3C_RFC_4115=3,
	 SSE2_QOS_POLICER_TYPE_API_2R3C_RFC_MEF5CF1=4,
	 SSE2_QOS_POLICER_TYPE_API_MAX=5,
}
impl Default for Sse2QosPolicerType {
	fn default() -> Self { Sse2QosPolicerType::SSE2_QOS_POLICER_TYPE_API_1R2C }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum Sse2QosActionType {
	 SSE2_QOS_ACTION_API_DROP=0,
	 SSE2_QOS_ACTION_API_TRANSMIT=1,
	 SSE2_QOS_ACTION_API_MARK_AND_TRANSMIT=2,
}
impl Default for Sse2QosActionType {
	fn default() -> Self { Sse2QosActionType::SSE2_QOS_ACTION_API_DROP }
}
