/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
// Implementation for sdl_rule
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SdlRule {
	pub lcl: Prefix,
	pub action_index: u32,
	pub tag: FixedSizeString<typenum::U64>,
}
// Implementation for sdl_rule_v2
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SdlRuleV2 {
	pub rmt: Prefix,
	pub action_index: u32,
	pub tag: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum TransportProto {
	 TRANSPORT_PROTO_API_TCP=0,
	 TRANSPORT_PROTO_API_UDP=1,
	 TRANSPORT_PROTO_API_NONE=2,
	 TRANSPORT_PROTO_API_TLS=3,
	 TRANSPORT_PROTO_API_QUIC=4,
}
impl Default for TransportProto {
	fn default() -> Self { TransportProto::TRANSPORT_PROTO_API_TCP }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum RtBackendEngine {
	 RT_BACKEND_ENGINE_API_DISABLE=0,
	 RT_BACKEND_ENGINE_API_RULE_TABLE=1,
	 RT_BACKEND_ENGINE_API_NONE=2,
	 RT_BACKEND_ENGINE_API_SDL=3,
}
impl Default for RtBackendEngine {
	fn default() -> Self { RtBackendEngine::RT_BACKEND_ENGINE_API_DISABLE }
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u32)]
pub enum SessionRuleScope {
	 SESSION_RULE_SCOPE_API_GLOBAL=0,
	 SESSION_RULE_SCOPE_API_LOCAL=1,
	 SESSION_RULE_SCOPE_API_BOTH=2,
}
impl Default for SessionRuleScope {
	fn default() -> Self { SessionRuleScope::SESSION_RULE_SCOPE_API_GLOBAL }
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_attach_5f4a260d)]
pub struct AppAttach {
	pub client_index: u32,
	pub context: u32,
	pub options: FixedSizeArray<u64, typenum::U18>,
	pub namespace_id: VariableSizeString,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_attach_reply_5c89c3b0)]
pub struct AppAttachReply {
	pub context: u32,
	pub retval: i32,
	pub app_mq: u64,
	pub vpp_ctrl_mq: u64,
	pub vpp_ctrl_mq_thread: u8,
	pub app_index: u32,
	pub n_fds: u8,
	pub fd_flags: u8,
	pub segment_size: u32,
	pub segment_handle: u64,
	pub segment_name: VariableSizeString,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(application_detach_51077d14)]
pub struct ApplicationDetach {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(application_detach_reply_e8d4e804)]
pub struct ApplicationDetachReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_add_cert_key_pair_02eb8016)]
pub struct AppAddCertKeyPair {
	pub client_index: u32,
	pub context: u32,
	pub cert_len: u16,
	pub certkey_len: u16,
	pub certkey: VariableSizeArray<u8>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_add_cert_key_pair_reply_b42958d0)]
pub struct AppAddCertKeyPairReply {
	pub context: u32,
	pub retval: i32,
	pub index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_del_cert_key_pair_8ac76db6)]
pub struct AppDelCertKeyPair {
	pub client_index: u32,
	pub context: u32,
	pub index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_del_cert_key_pair_reply_e8d4e804)]
pub struct AppDelCertKeyPairReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_worker_add_del_753253dc)]
pub struct AppWorkerAddDel {
	pub client_index: u32,
	pub context: u32,
	pub app_index: u32,
	pub wrk_index: u32,
	pub is_add: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_worker_add_del_reply_5735ffe7)]
pub struct AppWorkerAddDelReply {
	pub context: u32,
	pub retval: i32,
	pub wrk_index: u32,
	pub app_event_queue_address: u64,
	pub n_fds: u8,
	pub fd_flags: u8,
	pub segment_handle: u64,
	pub is_add: bool,
	pub segment_name: VariableSizeString,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_enable_disable_c264d7bf)]
pub struct SessionEnableDisable {
	pub client_index: u32,
	pub context: u32,
	pub is_enable: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_enable_disable_reply_e8d4e804)]
pub struct SessionEnableDisableReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_enable_disable_v2_f09fbf32)]
pub struct SessionEnableDisableV2 {
	pub client_index: u32,
	pub context: u32,
	pub rt_engine_type: RtBackendEngine,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_enable_disable_v2_reply_e8d4e804)]
pub struct SessionEnableDisableV2Reply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sapi_enable_disable_c264d7bf)]
pub struct SessionSapiEnableDisable {
	pub client_index: u32,
	pub context: u32,
	pub is_enable: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sapi_enable_disable_reply_e8d4e804)]
pub struct SessionSapiEnableDisableReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_6306aecb)]
pub struct AppNamespaceAddDel {
	pub client_index: u32,
	pub context: u32,
	pub secret: u64,
	pub sw_if_index: InterfaceIndex,
	pub ip4_fib_id: u32,
	pub ip6_fib_id: u32,
	pub namespace_id: VariableSizeString,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_v4_42c1d824)]
pub struct AppNamespaceAddDelV4 {
	pub client_index: u32,
	pub context: u32,
	pub secret: u64,
	pub is_add: bool,
	pub sw_if_index: InterfaceIndex,
	pub ip4_fib_id: u32,
	pub ip6_fib_id: u32,
	pub namespace_id: FixedSizeString<typenum::U64>,
	pub sock_name: VariableSizeString,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_v4_reply_85137120)]
pub struct AppNamespaceAddDelV4Reply {
	pub context: u32,
	pub retval: i32,
	pub appns_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_v2_ee0755cf)]
pub struct AppNamespaceAddDelV2 {
	pub client_index: u32,
	pub context: u32,
	pub secret: u64,
	pub sw_if_index: InterfaceIndex,
	pub ip4_fib_id: u32,
	pub ip6_fib_id: u32,
	pub namespace_id: FixedSizeString<typenum::U64>,
	pub netns: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_v3_8a7e40a1)]
pub struct AppNamespaceAddDelV3 {
	pub client_index: u32,
	pub context: u32,
	pub secret: u64,
	pub is_add: bool,
	pub sw_if_index: InterfaceIndex,
	pub ip4_fib_id: u32,
	pub ip6_fib_id: u32,
	pub namespace_id: FixedSizeString<typenum::U64>,
	pub netns: FixedSizeString<typenum::U64>,
	pub sock_name: VariableSizeString,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_reply_85137120)]
pub struct AppNamespaceAddDelReply {
	pub context: u32,
	pub retval: i32,
	pub appns_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_v2_reply_85137120)]
pub struct AppNamespaceAddDelV2Reply {
	pub context: u32,
	pub retval: i32,
	pub appns_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(app_namespace_add_del_v3_reply_85137120)]
pub struct AppNamespaceAddDelV3Reply {
	pub context: u32,
	pub retval: i32,
	pub appns_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_rule_add_del_82a90af5)]
pub struct SessionRuleAddDel {
	pub client_index: u32,
	pub context: u32,
	pub transport_proto: TransportProto,
	pub lcl: Prefix,
	pub rmt: Prefix,
	pub lcl_port: u16,
	pub rmt_port: u16,
	pub action_index: u32,
	pub is_add: bool,
	pub appns_index: u32,
	pub scope: SessionRuleScope,
	pub tag: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_rule_add_del_reply_e8d4e804)]
pub struct SessionRuleAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_rules_dump_51077d14)]
pub struct SessionRulesDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_rules_details_4ef746e7)]
pub struct SessionRulesDetails {
	pub context: u32,
	pub transport_proto: TransportProto,
	pub lcl: Prefix,
	pub rmt: Prefix,
	pub lcl_port: u16,
	pub rmt_port: u16,
	pub action_index: u32,
	pub appns_index: u32,
	pub scope: SessionRuleScope,
	pub tag: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_rules_v2_dump_51077d14)]
pub struct SessionRulesV2Dump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_rules_v2_details_f91993dc)]
pub struct SessionRulesV2Details {
	pub context: u32,
	pub transport_proto: TransportProto,
	pub lcl: Prefix,
	pub rmt: Prefix,
	pub lcl_port: u16,
	pub rmt_port: u16,
	pub action_index: u32,
	pub scope: SessionRuleScope,
	pub tag: FixedSizeString<typenum::U64>,
	pub count: u32,
	pub appns_index: VariableSizeArray<u32>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_add_del_faeb89fc)]
pub struct SessionSdlAddDel {
	pub client_index: u32,
	pub context: u32,
	pub appns_index: u32,
	pub is_add: bool,
	pub count: u32,
	pub r: VariableSizeArray<SdlRule>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_add_del_reply_e8d4e804)]
pub struct SessionSdlAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_add_del_v2_7f89d3fa)]
pub struct SessionSdlAddDelV2 {
	pub client_index: u32,
	pub context: u32,
	pub appns_index: u32,
	pub is_add: bool,
	pub count: u32,
	pub r: VariableSizeArray<SdlRuleV2>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_add_del_v2_reply_e8d4e804)]
pub struct SessionSdlAddDelV2Reply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_dump_51077d14)]
pub struct SessionSdlDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_details_9a8ef5d0)]
pub struct SessionSdlDetails {
	pub context: u32,
	pub lcl: Prefix,
	pub action_index: u32,
	pub appns_index: u32,
	pub tag: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_v2_dump_51077d14)]
pub struct SessionSdlV2Dump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_v2_details_0a057683)]
pub struct SessionSdlV2Details {
	pub context: u32,
	pub rmt: Prefix,
	pub action_index: u32,
	pub appns_index: u32,
	pub tag: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_v3_dump_51077d14)]
pub struct SessionSdlV3Dump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(session_sdl_v3_details_829e367f)]
pub struct SessionSdlV3Details {
	pub context: u32,
	pub rmt: Prefix,
	pub action_index: u32,
	pub tag: FixedSizeString<typenum::U64>,
	pub count: u32,
	pub appns_index: VariableSizeArray<u32>,
}
