/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::sfdp_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_tenant_add_del_f03b121c)]
pub struct SfdpTenantAddDel {
	pub client_index: u32,
	pub context: u32,
	pub tenant_id: u32,
	pub context_id: u32,
	pub is_del: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_tenant_add_del_reply_e8d4e804)]
pub struct SfdpTenantAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_services_6227a034)]
pub struct SfdpSetServices {
	pub client_index: u32,
	pub context: u32,
	pub tenant_id: u32,
	pub dir: SfdpSessionDirection,
	pub n_services: u8,
	pub services: VariableSizeArray<SfdpServiceName>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_services_reply_e8d4e804)]
pub struct SfdpSetServicesReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_session_dump_51077d14)]
pub struct SfdpSessionDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_session_details_3eaab6b9)]
pub struct SfdpSessionDetails {
	pub context: u32,
	pub session_id: u64,
	pub thread_index: u32,
	pub tenant_id: u32,
	pub session_idx: u32,
	pub session_type: SfdpSessionType,
	pub protocol: IpProto,
	pub state: SfdpSessionState,
	pub remaining_time: f64,
	pub forward_bitmap: u64,
	pub reverse_bitmap: u64,
	pub n_keys: u8,
	pub keys: VariableSizeArray<SfdpSessionKey>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_kill_session_1a16d196)]
pub struct SfdpKillSession {
	pub client_index: u32,
	pub context: u32,
	pub session_index: u32,
	pub is_all: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_kill_session_reply_e8d4e804)]
pub struct SfdpKillSessionReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_tenant_dump_51077d14)]
pub struct SfdpTenantDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_tenant_details_128e06c3)]
pub struct SfdpTenantDetails {
	pub context: u32,
	pub index: u32,
	pub context_id: u32,
	pub forward_bitmap: u64,
	pub reverse_bitmap: u64,
	pub n_timeout: u32,
	pub timeout: VariableSizeArray<u32>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_timeout_36440b87)]
pub struct SfdpSetTimeout {
	pub client_index: u32,
	pub context: u32,
	pub tenant_id: u32,
	pub timeout_id: u32,
	pub timeout_value: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_timeout_reply_e8d4e804)]
pub struct SfdpSetTimeoutReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_sp_node_e721277f)]
pub struct SfdpSetSpNode {
	pub client_index: u32,
	pub context: u32,
	pub tenant_id: u32,
	pub sp_node: SfdpSpNode,
	pub node_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_sp_node_reply_e8d4e804)]
pub struct SfdpSetSpNodeReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_icmp_error_node_90d10424)]
pub struct SfdpSetIcmpErrorNode {
	pub client_index: u32,
	pub context: u32,
	pub tenant_id: u32,
	pub is_ip6: bool,
	pub node_index: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_set_icmp_error_node_reply_e8d4e804)]
pub struct SfdpSetIcmpErrorNodeReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_service_dump_51077d14)]
pub struct SfdpServiceDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_service_details_2a8d1427)]
pub struct SfdpServiceDetails {
	pub context: u32,
	pub node_name: FixedSizeString<typenum::U32>,
	pub scope: FixedSizeString<typenum::U32>,
	pub is_terminal: bool,
	pub index: u8,
}
