/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::interface_types::*;
use crate::sr_types::*;
use crate::sr_mobile_types::*;
// Implementation for srv6_sid_list
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Srv6SidList {
	pub num_sids: u8,
	pub weight: u32,
	pub sids: FixedSizeArray<Ip6Address, typenum::U16>,
}
// Implementation for srv6_sid_list_with_sl_index
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Srv6SidListWithSlIndex {
	pub num_sids: u8,
	pub weight: u32,
	pub sl_index: u32,
	pub sids: FixedSizeArray<Ip6Address, typenum::U16>,
}
#[derive(Debug, Clone, Serialize_repr, Deserialize_repr)]
#[repr(u8)]
pub enum SrPolicyType {
	 SR_API_POLICY_TYPE_DEFAULT=0,
	 SR_API_POLICY_TYPE_SPRAY=1,
	 SR_API_POLICY_TYPE_TEF=2,
}
impl Default for SrPolicyType {
	fn default() -> Self { SrPolicyType::SR_API_POLICY_TYPE_DEFAULT }
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_mobile_localsid_add_del_b85a7ed7)]
pub struct SrMobileLocalsidAddDel {
	pub client_index: u32,
	pub context: u32,
	pub is_del: bool,
	pub localsid_prefix: Ip6Prefix,
	pub behavior: FixedSizeString<typenum::U64>,
	pub fib_table: u32,
	pub local_fib_table: u32,
	pub drop_in: bool,
	pub nhtype: SrMobileNhtype,
	pub sr_prefix: Ip6Prefix,
	pub v4src_addr: Ip4Address,
	pub v4src_position: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_mobile_localsid_add_del_reply_e8d4e804)]
pub struct SrMobileLocalsidAddDelReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_mobile_policy_add_8f051658)]
pub struct SrMobilePolicyAdd {
	pub client_index: u32,
	pub context: u32,
	pub bsid_addr: Ip6Address,
	pub sr_prefix: Ip6Prefix,
	pub v6src_prefix: Ip6Prefix,
	pub behavior: FixedSizeString<typenum::U64>,
	pub fib_table: u32,
	pub local_fib_table: u32,
	pub encap_src: Ip6Address,
	pub drop_in: bool,
	pub nhtype: SrMobileNhtype,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_mobile_policy_add_reply_e8d4e804)]
pub struct SrMobilePolicyAddReply {
	pub context: u32,
	pub retval: i32,
}
