/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
pub use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::interface_types::*;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_pt_iface_dump_51077d14)]
pub struct SrPtIfaceDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_pt_iface_details_1f472f85)]
pub struct SrPtIfaceDetails {
	pub context: u32,
	pub sw_if_index: InterfaceIndex,
	pub id: u16,
	pub ingress_load: u8,
	pub egress_load: u8,
	pub tts_template: u8,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_pt_iface_add_852c0cda)]
pub struct SrPtIfaceAdd {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_index: InterfaceIndex,
	pub id: u16,
	pub ingress_load: u8,
	pub egress_load: u8,
	pub tts_template: u8,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_pt_iface_add_reply_e8d4e804)]
pub struct SrPtIfaceAddReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_pt_iface_del_f9e6675e)]
pub struct SrPtIfaceDel {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_index: InterfaceIndex,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sr_pt_iface_del_reply_e8d4e804)]
pub struct SrPtIfaceDelReply {
	pub context: u32,
	pub retval: i32,
}
