/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
use crate::ip_types::*;
use crate::sfdp_types::*;
#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq)]
pub enum SfdpTcpCheckSessionFlags {
	 SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_RESP_SYN=1,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_INIT_ACK_TO_SYN=2,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_RESP_ACK_TO_SYN=4,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_FIN_INIT=8,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_FIN_RESP=16,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_ACK_TO_FIN_INIT=32,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_ACK_TO_FIN_RESP=64,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_ESTABLISHED=128,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_REMOVING=256,
	 SFDP_API_TCP_CHECK_SESSION_FLAG_BLOCKED=512,
}
impl Default for SfdpTcpCheckSessionFlags {
	fn default() -> Self { SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_RESP_SYN }
}
impl AsEnumFlag for SfdpTcpCheckSessionFlags {
	 fn as_u32(data: &Self) -> u32{
		 *data as u32
	 }
	 fn from_u32(data: u32) -> Self{
		 match data{
			 1 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_RESP_SYN,
			 2 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_INIT_ACK_TO_SYN,
			 4 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_WAIT_FOR_RESP_ACK_TO_SYN,
			 8 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_FIN_INIT,
			 16 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_FIN_RESP,
			 32 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_ACK_TO_FIN_INIT,
			 64 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_SEEN_ACK_TO_FIN_RESP,
			 128 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_ESTABLISHED,
			 256 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_REMOVING,
			 512 => SfdpTcpCheckSessionFlags::SFDP_API_TCP_CHECK_SESSION_FLAG_BLOCKED,
			_ => panic!("Invalid Enum Descriminant")
		 }
	 }
	 fn size_of_enum_flag() -> u32{
		 32 as u32
	}
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_tcp_session_dump_51077d14)]
pub struct SfdpTcpSessionDump {
	pub client_index: u32,
	pub context: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(sfdp_tcp_session_details_4bd58888)]
pub struct SfdpTcpSessionDetails {
	pub context: u32,
	pub session_id: u64,
	pub thread_index: u32,
	pub tenant_id: u32,
	pub session_idx: u32,
	pub session_type: SfdpSessionType,
	 pub flags: EnumFlag<SfdpTcpCheckSessionFlags>,
	pub n_keys: u8,
	pub keys: VariableSizeArray<SfdpSessionKey>,
}
