/*
   Autogenerated Data, Do not Edit!
*/
#![allow(dead_code,unused_mut,unused_variables,unused_must_use,non_camel_case_types,unused_imports,non_snake_case)]
use vpp_api_macros::{VppMessage,VppUnionIdent};
use std::convert::TryInto;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use vpp_api_encoding::typ::*;
pub use vpp_api_encoding;
use vpp_api_message::VppApiMessage;
use serde_repr::{Serialize_repr, Deserialize_repr};
use typenum;
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_add_0f60688a)]
pub struct TmSysNodeAdd {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub parent_node_id: i32,
	pub node_id: u32,
	pub weight: u32,
	pub shaper_id: i32,
	pub lvl: u32,
	pub priority: u32,
	pub flow_name: FixedSizeString<typenum::U64>,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_add_reply_e8d4e804)]
pub struct TmSysNodeAddReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_suspend_0cfbb348)]
pub struct TmSysNodeSuspend {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub tm_node_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_suspend_reply_e8d4e804)]
pub struct TmSysNodeSuspendReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_resume_0cfbb348)]
pub struct TmSysNodeResume {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub tm_node_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_resume_reply_e8d4e804)]
pub struct TmSysNodeResumeReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_delete_0cfbb348)]
pub struct TmSysNodeDelete {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub tm_node_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_delete_reply_e8d4e804)]
pub struct TmSysNodeDeleteReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_shaper_profile_create_65d7728b)]
pub struct TmSysShaperProfileCreate {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub tm_shaper_id: u32,
	pub is_pkt_mode: u8,
	pub shaper_commit_rate: u64,
	pub shaper_commit_burst: u64,
	pub shaper_peak_rate: u64,
	pub shaper_peak_burst: u64,
	pub shaper_len_adjust: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_shaper_profile_create_reply_e8d4e804)]
pub struct TmSysShaperProfileCreateReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_shaper_update_22ab653b)]
pub struct TmSysNodeShaperUpdate {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub shaper_id: i32,
	pub node_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_shaper_update_reply_e8d4e804)]
pub struct TmSysNodeShaperUpdateReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_shaper_profile_delete_ed96e391)]
pub struct TmSysShaperProfileDelete {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub shaper_id: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_shaper_profile_delete_reply_e8d4e804)]
pub struct TmSysShaperProfileDeleteReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_sched_weight_update_8f0ff13e)]
pub struct TmSysNodeSchedWeightUpdate {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub node_id: u32,
	pub weight: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_sched_weight_update_reply_e8d4e804)]
pub struct TmSysNodeSchedWeightUpdateReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_get_capabilities_991d3cc9)]
pub struct TmSysGetCapabilities {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_get_capabilities_reply_e8d4e804)]
pub struct TmSysGetCapabilitiesReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_level_get_capabilities_1b2a3c26)]
pub struct TmSysLevelGetCapabilities {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub level: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_level_get_capabilities_reply_e8d4e804)]
pub struct TmSysLevelGetCapabilitiesReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_read_stats_a98a5d55)]
pub struct TmSysNodeReadStats {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
	pub node_id: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_node_read_stats_reply_e8d4e804)]
pub struct TmSysNodeReadStatsReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_start_tm_991d3cc9)]
pub struct TmSysStartTm {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_start_tm_reply_e8d4e804)]
pub struct TmSysStartTmReply {
	pub context: u32,
	pub retval: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_stop_tm_991d3cc9)]
pub struct TmSysStopTm {
	pub client_index: u32,
	pub context: u32,
	pub sw_if_idx: u32,
}
#[derive(Debug, Clone, Serialize, Deserialize, VppMessage)]
#[message_name_and_crc(tm_sys_stop_tm_reply_e8d4e804)]
pub struct TmSysStopTmReply {
	pub context: u32,
	pub retval: i32,
}
